# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ip6nGmPoy6pNa9qvdto_Q4SHjDdww3NS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the data
demographics_data = pd.read_csv('sample_data/demographics.csv')
sensing_data = pd.read_csv('sample_data/sensing.csv')

# Demographics breakdown with percentages
demographics_breakdown = demographics_data.groupby(['race', 'gender']).size().reset_index(name='count')
demographics_breakdown['percentage'] = (demographics_breakdown['count'] / demographics_data.shape[0]) * 100
print(demographics_breakdown)